<?php


namespace Kinicart\Objects\Payment\Stripe;


use Kinikit\Persistence\ORM\ActiveRecord;

/**
 * Class StripeCustomer
 * @package Kinicart\Objects\Payment\Stripe
 *
 * @table kc_stripe_customer
 */
class StripeCustomer extends ActiveRecord {

    /**
     * @primaryKey
     * @var string
     */
    private $accountId;

    /**
     * Customer Id generated by Stripe
     *
     * @var string
     */
    private $customerId;

    /**
     * @return string
     */
    public function getAccountId() {
        return $this->accountId;
    }

    /**
     * @param string $accountId
     */
    public function setAccountId($accountId) {
        $this->accountId = $accountId;
    }

    /**
     * @return string
     */
    public function getCustomerId() {
        return $this->customerId;
    }

    /**
     * @param string $customerId
     */
    public function setCustomerId($customerId) {
        $this->customerId = $customerId;
    }



}
